import { getSession } from '@/lib/session'

// Whitelisted query params that the Electric client includes on shape
// requests. Everything else (including any client-supplied `where`) is
// dropped — we always inject `where` from the session for user-scoped
// tables so clients can't widen their own visibility.
const FORWARDED_PARAMS = ['live', 'table', 'handle', 'offset', 'cursor', 'columns'] as const

// Tables any authenticated user can read, scoped to their own user_id.
// praamid_credentials is deliberately NOT here — rows contain encrypted
// access tokens and are read server-side only. See lib/collections.ts.
const USER_SCOPED_TABLES = new Set(['trips', 'trip_options', 'tickets'])

// Tables only admins can read, returned unfiltered.
const ADMIN_ONLY_TABLES = new Set(['user', 'audit_logs', 'settings'])

function quoteIdent(id: string) {
  return `"${id.replace(/"/g, '""')}"`
}

export async function GET(request: Request) {
  const session = await getSession()
  if (!session) {
    return new Response('unauthorized', { status: 401 })
  }

  const electricUrl = process.env.ELECTRIC_URL
  if (!electricUrl) {
    return new Response('electric not configured', { status: 500 })
  }

  const incoming = new URL(request.url)
  const table = incoming.searchParams.get('table')
  if (!table) {
    return new Response('missing table', { status: 400 })
  }

  const isUserScoped = USER_SCOPED_TABLES.has(table)
  const isAdminOnly = ADMIN_ONLY_TABLES.has(table)
  if (!isUserScoped && !isAdminOnly) {
    return new Response('forbidden', { status: 403 })
  }

  const isAdmin = session.user.role === 'admin'
  if (isAdminOnly && !isAdmin) {
    return new Response('forbidden', { status: 403 })
  }

  // Admin scope opt-in: admins can request unfiltered access to user-scoped
  // tables by passing ?scope=admin (needed for the /admin dashboard which
  // shows every user's trips). Default stays user-scoped so admins still see
  // only their own rows on the regular home page.
  const adminScope = incoming.searchParams.get('scope') === 'admin'
  if (adminScope && !isAdmin) {
    return new Response('forbidden', { status: 403 })
  }

  const origin = new URL('/v1/shape', electricUrl)
  for (const key of FORWARDED_PARAMS) {
    const value = incoming.searchParams.get(key)
    if (value !== null) origin.searchParams.set(key, value)
  }

  if (isUserScoped && !adminScope) {
    // Electric's `where` doesn't support parameterized queries — user.id is
    // generated by better-auth (UUID) so it doesn't need escaping, but be
    // defensive: reject anything that isn't plain ascii id chars.
    const userId = session.user.id
    if (!/^[a-zA-Z0-9_-]+$/.test(userId)) {
      return new Response('invalid session', { status: 500 })
    }
    origin.searchParams.set('where', `${quoteIdent('user_id')} = '${userId}'`)
  }

  const upstream = await fetch(origin, { headers: { accept: 'application/json' } })

  // fetch decompresses the body but keeps content-encoding/length headers,
  // which would break decoding in the browser.
  const headers = new Headers(upstream.headers)
  headers.delete('content-encoding')
  headers.delete('content-length')

  return new Response(upstream.body, {
    status: upstream.status,
    statusText: upstream.statusText,
    headers,
  })
}
